# =======================================================================
## Spring
# =======================================================================
spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  h2:
      console:
        enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
    username: customer-service

server:
  port: 8081